  name: Playwright Tests
  on:
    push:
        branches: [ main ]
  jobs:
    playwrighttests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: MESSAGE
              uses: echo ALL YOUR BASE ARE BELONG TO US
